### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by kodewdle** [kodewdle/ElvUI_FCT#1]
* [x]  Number Abbreviation, Short and Long, With commas or not
* [x]  Text and Animation offset add config for Animation mode
* [x]  Redo the configure functions so it updates the frames without Update All
* [x]  Rename the side option to Floating Combat Text (red color maybe?)
* [x]  Add my function to color the text fancy during animation/or maybe critical? so it will color the spell types like orange->purple or chaos flashing (must code this) *(**NOTE:** done as a basic version)*
* [x]  Add Text Critical scale option (currently it's a static increase)
* [x]  Finish spell exclusion code/config
* [x]  Add Locales
* [x]  Stacking (with over-time option)
* [ ]  Figure out why shake text doesn't work on nameplates? frame shake works on both and text shake works on unitframes. dono
* [ ]  Spell type Animation/Color/Font
* [ ]  Cartwheel animation
* [ ]  Zoom animation
* [ ]  Test Toggle :thinking: 
* [ ]  Add Justify text options
* [ ]  Elv wants copy settings?
* [ ]  Separate option for suffix and prefix
* [ ]  Split healing and damage for single unit?
* [ ]  Text Strata to it can be behind nameplates?
* [ ]  Add specific settings for environmental damage (fall, fatigue, lava, etc) maybe?
* [ ]  Add option to ignore types (Immune, Missing, Parry, etc)
* [ ]  Add option for Guardian (Imps, Tyrant, etc) damage to be displayed
